export type Arcana = {
  id: number;
  name: string;
  description: string;
  personality: string;
  loveMeaning: string;
  moneyMeaning: string;
  karmicLesson: string;
  affirmation: string;
  strengths: string[];
  challenges: string[];
};

export const arcanaMeanings: Record<number, Arcana> = {
  1: {
    id: 1,
    name: 'The Magician',
    description: 'Manifestation, new beginnings, taking action',
    personality: 'You are a natural creator with the power to transform ideas into reality. Your willpower and focus are your greatest assets.',
    loveMeaning: 'In love, you attract through confidence and authenticity. You have the power to create the relationship you desire.',
    moneyMeaning: 'Financial success comes through your skills and initiative. Multiple income streams are possible for you.',
    karmicLesson: 'Learning to use your powers responsibly and not for manipulation.',
    affirmation: 'I have all the tools I need to create my reality.',
    strengths: ['Manifestation', 'Creativity', 'Willpower', 'Resourcefulness'],
    challenges: ['Manipulation', 'Deception', 'Lack of follow-through'],
  },
  2: {
    id: 2,
    name: 'The High Priestess',
    description: 'Intuition, mystery, inner knowledge',
    personality: 'You possess deep wisdom and intuition. The unseen world speaks to you, and you trust your inner voice.',
    loveMeaning: 'Love for you is a spiritual journey. You seek soul connections and profound emotional depth.',
    moneyMeaning: 'Your intuition guides financial decisions. Trust your gut in investments and career moves.',
    karmicLesson: 'Balancing inner wisdom with outer expression.',
    affirmation: 'I trust my intuition to guide me.',
    strengths: ['Intuition', 'Wisdom', 'Patience', 'Mystery'],
    challenges: ['Secrecy', 'Hidden motives', 'Withdrawal'],
  },
  3: {
    id: 3,
    name: 'The Empress',
    description: 'Abundance, fertility, nurturing',
    personality: 'You embody creativity and nurturing energy. Life flourishes around you through your care and attention.',
    loveMeaning: 'You bring warmth and abundance to relationships. Love grows and blossoms in your presence.',
    moneyMeaning: 'Financial abundance flows naturally to you. Your creative ventures bring prosperity.',
    karmicLesson: 'Nurturing others without depleting yourself.',
    affirmation: 'I am worthy of abundance in all forms.',
    strengths: ['Nurturing', 'Creativity', 'Abundance', 'Fertility'],
    challenges: ['Over-giving', 'Dependence', 'Smothering'],
  },
  4: {
    id: 4,
    name: 'The Emperor',
    description: 'Authority, structure, leadership',
    personality: 'You are a natural leader with strong organizational abilities. You create order from chaos.',
    loveMeaning: 'In relationships, you seek stability and commitment. You protect and provide for loved ones.',
    moneyMeaning: 'Financial stability through disciplined planning. Leadership roles bring prosperity.',
    karmicLesson: 'Leading with compassion, not just authority.',
    affirmation: 'I create structure that serves the highest good.',
    strengths: ['Leadership', 'Authority', 'Structure', 'Protection'],
    challenges: ['Rigidity', 'Control', 'Dominance'],
  },
  5: {
    id: 5,
    name: 'The Hierophant',
    description: 'Tradition, spirituality, conformity',
    personality: 'You seek meaning through established wisdom and traditions. You bridge the sacred and mundane.',
    loveMeaning: 'You value commitment and traditional relationships. Marriage and family are important.',
    moneyMeaning: 'Financial success through conventional paths. Institutions and organizations favor you.',
    karmicLesson: 'Finding personal truth within or beyond tradition.',
    affirmation: 'I honor wisdom from all traditions.',
    strengths: ['Wisdom', 'Teaching', 'Tradition', 'Spiritual guidance'],
    challenges: ['Dogma', 'Rigidity', 'Conformity'],
  },
  6: {
    id: 6,
    name: 'The Lovers',
    description: 'Love, harmony, choices',
    personality: 'You embody the energy of connection and choice. Relationships are central to your journey.',
    loveMeaning: 'Deep romantic connections and soulmate unions. Love brings important life lessons.',
    moneyMeaning: 'Partnerships enhance prosperity. Joint ventures and collaborations succeed.',
    karmicLesson: 'Making choices aligned with your highest self.',
    affirmation: 'I choose love in all my decisions.',
    strengths: ['Harmony', 'Connection', 'Choice', 'Communication'],
    challenges: ['Indecision', 'Dependency', 'Temptation'],
  },
  7: {
    id: 7,
    name: 'The Chariot',
    description: 'Victory, determination, willpower',
    personality: 'You are a driven achiever who overcomes obstacles through sheer will and determination.',
    loveMeaning: 'You pursue love with determination. Relationships require balancing opposing forces.',
    moneyMeaning: 'Financial victory through focused effort. Career advancement and recognition.',
    karmicLesson: 'Controlling without being controlling.',
    affirmation: 'I move forward with focused determination.',
    strengths: ['Determination', 'Victory', 'Willpower', 'Focus'],
    challenges: ['Aggression', 'Lack of direction', 'Control'],
  },
  8: {
    id: 8,
    name: 'Strength',
    description: 'Courage, patience, inner power',
    personality: 'You possess quiet strength and the power to tame your inner beasts through compassion.',
    loveMeaning: 'Love requires patience and gentle persistence. Relationships grow through acceptance.',
    moneyMeaning: 'Financial success through steady persistence. Your inner strength attracts abundance.',
    karmicLesson: 'Gentleness is true strength.',
    affirmation: 'I have the strength to overcome any obstacle.',
    strengths: ['Courage', 'Patience', 'Compassion', 'Inner power'],
    challenges: ['Self-doubt', 'Impatience', 'Force over gentleness'],
  },
  9: {
    id: 9,
    name: 'The Hermit',
    description: 'Solitude, introspection, guidance',
    personality: 'You are a seeker of inner truth. Solitude recharges and enlightens you.',
    loveMeaning: 'You need space within relationships. Love deepens through shared spiritual growth.',
    moneyMeaning: 'Financial wisdom comes from careful planning. Independence in career serving.',
    karmicLesson: 'Sharing inner light with others.',
    affirmation: 'I find wisdom in my solitude.',
    strengths: ['Wisdom', 'Introspection', 'Guidance', 'Patience'],
    challenges: ['Isolation', 'Loneliness', 'Withdrawal'],
  },
  10: {
    id: 10,
    name: 'Wheel of Fortune',
    description: 'Fate, cycles, opportunity',
    personality: 'You understand life\'s cycles and adapt to change with grace.',
    loveMeaning: 'Relationships have karmic connections. Love arrives at the right divine timing.',
    moneyMeaning: 'Fortune favors you at key moments. Financial cycles bring ups and downs.',
    karmicLesson: 'Accepting what cannot be controlled.',
    affirmation: 'I trust the universe\'s perfect timing.',
    strengths: ['Adaptability', 'Optimism', 'Vision', 'Timing'],
    challenges: ['Passivity', 'Superstition', 'Greed'],
  },
  11: {
    id: 11,
    name: 'Justice',
    description: 'Fairness, karma, truth',
    personality: 'You have a strong sense of justice and fairness. Truth and balance guide your actions.',
    loveMeaning: 'Relationships require fairness and balance. Legal commitments may be significant.',
    moneyMeaning: 'Fair dealings bring prosperity. Contracts and legal matters favor you.',
    karmicLesson: 'Balancing mercy with justice.',
    affirmation: 'I act with fairness and integrity.',
    strengths: ['Fairness', 'Truth', 'Balance', 'Justice'],
    challenges: ['Rigidity', 'Judgment', 'Coldness'],
  },
  12: {
    id: 12,
    name: 'The Hanged Man',
    description: 'Surrender, new perspective, pause',
    personality: 'You find wisdom through letting go. Suspension leads to profound insights.',
    loveMeaning: 'Relationships require sacrifice and new perspectives. Love teaches surrender.',
    moneyMeaning: 'Financial success may require releasing control. Delays lead to better opportunities.',
    karmicLesson: 'Letting go to receive greater good.',
    affirmation: 'I release control to gain new perspective.',
    strengths: ['Surrender', 'Perspective', 'Patience', 'Insight'],
    challenges: ['Martyrdom', 'Indecision', 'Delay'],
  },
  13: {
    id: 13,
    name: 'Death',
    description: 'Transformation, endings, rebirth',
    personality: 'You embrace transformation and understand that endings birth new beginnings.',
    loveMeaning: 'Relationships transform you. Love may require letting go of old patterns.',
    moneyMeaning: 'Financial transformation through releasing old structures. Career rebirth.',
    karmicLesson: 'Embracing change without fear.',
    affirmation: 'I release the old to welcome the new.',
    strengths: ['Transformation', 'Release', 'Rebirth', 'Courage'],
    challenges: ['Fear of change', 'Resistance', 'Stagnation'],
  },
  14: {
    id: 14,
    name: 'Temperance',
    description: 'Balance, moderation, patience',
    personality: 'You bring harmony through blending opposites. Moderation is your path to mastery.',
    loveMeaning: 'Relationships require balance and patience. Love grows through harmony.',
    moneyMeaning: 'Steady, balanced approach to finances. Moderate success through patience.',
    karmicLesson: 'Finding middle ground in extremes.',
    affirmation: 'I bring harmony to all aspects of life.',
    strengths: ['Balance', 'Patience', 'Harmony', 'Moderation'],
    challenges: ['Procrastination', 'Indecision', 'Excessive compromise'],
  },
  15: {
    id: 15,
    name: 'The Devil',
    description: 'Bondage, materialism, shadow',
    personality: 'You understand human desires and attachments. Shadow work leads to liberation.',
    loveMeaning: 'Relationships may have karmic ties or unhealthy patterns. Liberation through awareness.',
    moneyMeaning: 'Material success possible but may bring attachments. Financial chains to examine.',
    karmicLesson: 'Breaking free from self-imposed limitations.',
    affirmation: 'I release all chains that bind me.',
    strengths: ['Ambition', 'Manifestation', 'Material success', 'Shadow awareness'],
    challenges: ['Attachment', 'Addiction', 'Materialism'],
  },
  16: {
    id: 16,
    name: 'The Tower',
    description: 'Sudden change, revelation, upheaval',
    personality: 'You catalyze transformation through breakdown. False structures crumble for truth.',
    loveMeaning: 'Relationships may undergo sudden transformation. Love liberates what needs release.',
    moneyMeaning: 'Financial shakeups clear old patterns. Collapse leads to rebuilding.',
    karmicLesson: 'Trusting breakdown as breakthrough.',
    affirmation: 'I embrace transformation in all forms.',
    strengths: ['Transformation', 'Truth', 'Liberation', 'Revelation'],
    challenges: ['Disaster', 'Upheaval', 'Resistance to change'],
  },
  17: {
    id: 17,
    name: 'The Star',
    description: 'Hope, inspiration, renewal',
    personality: 'You shine light after darkness. Hope and inspiration flow through you naturally.',
    loveMeaning: 'Relationships bring hope and healing. Love renews and inspires.',
    moneyMeaning: 'Financial renewal and hope. Opportunities align with your highest vision.',
    karmicLesson: 'Maintaining hope through all circumstances.',
    affirmation: 'I am a channel for divine light and hope.',
    strengths: ['Hope', 'Inspiration', 'Healing', 'Renewal'],
    challenges: ['Disconnection', 'Despair', 'Blocked creativity'],
  },
  18: {
    id: 18,
    name: 'The Moon',
    description: 'Illusion, intuition, dreams',
    personality: 'You navigate between worlds, understanding that appearances deceive.',
    loveMeaning: 'Love has mysterious depths. Relationships require trusting intuition over appearances.',
    moneyMeaning: 'Financial intuition guides you. Trust instincts over surface data.',
    karmicLesson: 'Seeing through illusion to truth.',
    affirmation: 'I trust my inner vision to guide me.',
    strengths: ['Intuition', 'Creativity', 'Depth', 'Dreams'],
    challenges: ['Illusion', 'Fear', 'Confusion'],
  },
  19: {
    id: 19,
    name: 'The Sun',
    description: 'Joy, success, vitality',
    personality: 'You radiate warmth and positivity. Success and joy follow your authentic expression.',
    loveMeaning: 'Relationships bring joy and fulfillment. Love shines brightly and openly.',
    moneyMeaning: 'Financial success and prosperity flow abundantly. Career recognition.',
    karmicLesson: 'Sharing your light generously.',
    affirmation: 'I shine my light and attract abundance.',
    strengths: ['Joy', 'Success', 'Vitality', 'Optimism'],
    challenges: ['Overconfidence', 'Burnout', 'Superficiality'],
  },
  20: {
    id: 20,
    name: 'Judgement',
    description: 'Awakening, rebirth, calling',
    personality: 'You hear your soul\'s calling and answer with purpose. Awakening is your journey.',
    loveMeaning: 'Relationships have karmic purpose. Love calls you to your highest self.',
    moneyMeaning: 'Financial decisions require soul alignment. Career calling becomes clear.',
    karmicLesson: 'Answering the call to your highest purpose.',
    affirmation: 'I answer the call of my highest self.',
    strengths: ['Awakening', 'Purpose', 'Reckoning', 'Calling'],
    challenges: ['Self-doubt', 'Ignoring the call', 'Fear'],
  },
  21: {
    id: 21,
    name: 'The World',
    description: 'Completion, integration, achievement',
    personality: 'You embody wholeness and completion. Cycles end in your mastery and new ones begin.',
    loveMeaning: 'Relationships reach fulfillment. Love completes and integrates you.',
    moneyMeaning: 'Financial success through completion of goals. Global opportunities.',
    karmicLesson: 'Integrating all experiences into wisdom.',
    affirmation: 'I am complete and ready for new beginnings.',
    strengths: ['Completion', 'Integration', 'Achievement', 'Wholeness'],
    challenges: ['Lack of closure', 'Seeking outside self', 'Delayed endings'],
  },
  22: {
    id: 22,
    name: 'The Fool',
    description: 'New beginnings, innocence, faith',
    personality: 'You embody infinite potential and the courage to take leaps of faith.',
    loveMeaning: 'Love is a new adventure. Relationships require trust and openness.',
    moneyMeaning: 'Financial opportunities through taking calculated risks. New ventures.',
    karmicLesson: 'Trusting life\'s journey without guarantees.',
    affirmation: 'I embrace each moment with childlike wonder.',
    strengths: ['Beginner\'s mind', 'Spontaneity', 'Faith', 'Adventure'],
    challenges: ['Recklessness', 'Naivety', 'Lack of planning'],
  },
};

export function getArcana(id: number): Arcana {
  return arcanaMeanings[id] || arcanaMeanings[22];
}
